---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: myweb-monitoring
  endpoints:
    - port: http-metrics
      path: /metrics
